[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/proxy/*"
  to = "http://13.239.246.72:8080/api"
  status = 200
  force = true